# Generated by Django 5.0.3 on 2024-05-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('sleep_duration', models.DurationField(blank=True, null=True)),
                ('work_system', models.CharField(choices=[('出勤', '出勤'), ('出張', '出張'), ('テレワーク', 'テレワーク'), ('休み', '休み')], max_length=100)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('expenditure', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('overall_mood', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField()),
            ],
        ),
    ]
