# Generated by Django 5.0.3 on 2024-05-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleApp', '0002_comment_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='sleep_duration',
        ),
        migrations.AddField(
            model_name='article',
            name='sleep_duration_hours',
            field=models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default=6),
            preserve_default=False,
        ),
    ]
