# Generated by Django 5.0.3 on 2024-05-05 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleApp', '0004_alter_article_expenditure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='sleep_duration_hours',
            new_name='sleep_duration',
        ),
    ]
