# Generated by Django 5.0.3 on 2024-05-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleApp', '0006_alter_article_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sentiment_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
