# Generated by Django x.x on YYYY-MM-DD HH:MM

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('sampleApp', '0007_article_sentiment_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_score', models.FloatField(blank=True, null=True)),
                ('weather_score', models.FloatField(blank=True, null=True)),
                ('work_system_score', models.FloatField(blank=True, null=True)),
                ('expenditure_score', models.FloatField(blank=True, null=True)),
                ('overall_mood_score', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]

        
