# Generated by Django 5.0.3 on 2024-05-16 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleApp', '0008_healthscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthscore',
            name='article',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='health_score', to='sampleApp.article'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthscore',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
