# Generated by Django 5.0.3 on 2024-05-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleApp', '0010_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthscore',
            name='overall_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthscore',
            name='sleep_duration_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
