# Generated by Django 5.0.3 on 2024-05-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleApp', '0011_healthscore_overall_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='save_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
