# Generated by Django 5.0.3 on 2024-06-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleApp', '0012_article_save_in_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='text',
            new_name='private_text',
        ),
        migrations.AddField(
            model_name='article',
            name='overtime_hours',
            field=models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='work_text',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
