# Generated by Django 5.0.3 on 2024-06-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleApp', '0014_rename_overall_score_healthscore_overtime_hours_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthscore',
            old_name='sentiment_score',
            new_name='private_text_score',
        ),
        migrations.RenameField(
            model_name='healthscore',
            old_name='text_score',
            new_name='work_text_score',
        ),
        migrations.RemoveField(
            model_name='article',
            name='sentiment_score',
        ),
    ]
