version: '3'

services:
  web:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    tty: true
    volumes:
      - ../:/workspace
    depends_on:
      - db


  db:
    image: postgres
    volumes:
        - postgres_data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: saku2238
        POSTGRES_DB: djangosample

  pgadmin4:
    image: dpage/pgadmin4
    ports:
        - 8888:80
    volumes:
        - pgadmin4_data:/var/lib/pgadmin
    environment:
        PGADMIN_DEFAULT_EMAIL: sakuenterforce@gmail.com
        PGADMIN_DEFAULT_PASSWORD: saku2238
    depends_on:
      - db

volumes:
    postgres_data:
    pgadmin4_data: