version: '3'

services:
  web:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.dev  # 開発用Dockerfile
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: djangSampleProject.settings.development  # 開発用の設定ファイルを指定
    command: python manage.py runserver 0.0.0.0:8000  # Django開発サーバーを使用
    volumes:
      - ../:/workspace
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5432:5432"  # 開発環境用ポート
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: dev_db

  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    volumes:
      - pgadmin4_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@example.com
      PGADMIN_DEFAULT_PASSWORD: dev_password
    depends_on:
      - db
